version: '3.4'

services:
  archz.auth.api:
    image: ${DOCKER_REGISTRY-}archzauthapi
    build:
      context: .
      dockerfile: src/Services/Auth/Archz.Auth.Api/Dockerfile

  postgres:
    image: postgres:14-alpine
    ports:
      - 5432:5432
    volumes:
      - ~/apps/postgres:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=S3cret
      - POSTGRES_USER=citizix_user
      - POSTGRES_DB=citizix_db

networks:
  archz:
    driver: bridge
