version: '3.4'

services:
  archz.users.api:
    image: ${DOCKER_REGISTRY-}archzusersapi
    build:
      context: .
      dockerfile: src/Services/Users/Archz.Users.Api/Dockerfile
    depends_on:
      - sql-server-users

  sql-server-users:
    image: mcr.microsoft.com/mssql/server:2022-latest
    ports:
      - "1433:1433"
    environment:
      - ACCEPT_EULA=Y
      - MSSQL_SA_PASSWORD=SystemAdmin@#$123

  archz.products.api:
    image: ${DOCKER_REGISTRY-}archzproductsapi
    build:
      context: .
      dockerfile: src/Services/Products/Archz.Products.Api/Dockerfile
    depends_on:
      - sql-server-products

  sql-server-products:
    image: mcr.microsoft.com/mssql/server:2022-latest
    ports:
      - "1434:1433"
    environment:
      - ACCEPT_EULA=Y
      - MSSQL_SA_PASSWORD=SystemAdmin@#$123

