version: '3.4'

services:
  archz.users.api:
    image: ${DOCKER_REGISTRY-}archzusersapi
    build:
      context: .
      dockerfile: src/Services/Users/Archz.Users.Api/Dockerfile
    depends_on:
      - sql-server

  sql-server:
    image: mcr.microsoft.com/mssql/server:2022-latest
    ports:
      - "1433:1433"
    environment:
      - ACCEPT_EULA=Y
      - MSSQL_SA_PASSWORD=SystemAdmin@#$123



